spring.application.name=attendance-service
spring.datasource.url=jdbc:postgresql://100.84.196.41:5432/mydb
spring.datasource.username=teammate
spring.datasource.password=StrongPassword123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
                         

server.port=${PORT:9090}


