spring.application.name=attendance-service
spring.datasource.url=jdbc:postgresql://db.vuvxmtuqsszhboedhvry.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Learning@9
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
