spring.application.name=salary_structure
spring.datasource.url=jdbc:postgresql://100.84.196.41:6432/mydb
spring.datasource.username=giribabu
spring.datasource.password=Giribabu@h
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2


# HikariCP Settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

server.port=${PORT:9092}


