#spring.application.name=salary_structure
#spring.datasource.url=jdbc:postgresql://100.84.196.41:6432/mydb
#spring.datasource.username=vanisree
#spring.datasource.password=Vanisree@m
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
##spring.datasource.hikari.maximum-pool-size=10
##spring.datasource.hikari.minimum-idle=2
#
#
## HikariCP Settings
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.connection-timeout=30000
#
#server.port=${PORT:9092}
#
#


spring.application.name=salary_structure

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://100.84.196.41:6432/mydb
spring.datasource.username=vanisree
spring.datasource.password=Vanisree@m

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ================= HIKARI =================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


# ================= SERVER =================
server.port=${PORT:9092}

# ================= LOGGING =================
logging.config=classpath:log4j2.xml
spring.main.banner-mode=off

