# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ems.postgres.database.azure.com:5432/postgres
spring.datasource.username=pgadmin
spring.datasource.password=Learning@9

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



server.port=${PORT:8080}