# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://100.84.196.41:5432/mydb
spring.datasource.username=teammate
spring.datasource.password=StrongPassword123

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true



server.port=${PORT:8080}